# Generated by Django 4.0.4 on 2022-05-25 09:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_colorproducts_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproducts',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.DeleteModel(
            name='ColorProducts',
        ),
    ]
