# Generated by Django 4.0.4 on 2022-05-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionproducts',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
