# Generated by Django 4.0.4 on 2022-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_discount_price_product_new_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('callback', models.BooleanField(default=False)),
            ],
        ),
    ]
