# Generated by Django 4.0.4 on 2022-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_сallback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сallback',
            new_name='CallBack',
        ),
    ]
