# Generated by Django 4.0.4 on 2022-05-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Наши преимущества', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Помощь', 'verbose_name_plural': 'Помощь'},
        ),
        migrations.AlterModelOptions(
            name='helpimages',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Помощь изображение'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Публичная оферта', 'verbose_name_plural': 'Публичная оферта'},
        ),
    ]
