# Generated by Django 4.0.4 on 2022-05-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_help_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.helpimages'),
        ),
    ]
