# Generated by Django 4.0.4 on 2022-05-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_help_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpimages',
            options={'verbose_name': 'Помощь', 'verbose_name_plural': 'Помощь'},
        ),
    ]
