# Generated by Django 4.0.4 on 2022-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_footerone_footertwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertwo',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
